### ISSUE TITLE
Game Lib

### ISSUE THREAD

**Issue by uduse** [TeamGorilla/GoBanana#3]
In `gobanana/game`:

- create `game.py` that stores a board, remembers game state, and know the transition function, you may also have `actions.py`, `board.py`, and other stuff as you wish

In `tests`:
- create `test_game.py` and have one or two tests that check your game implementation

**Comment by dem1995** [comment]
Update: the first part of this task is up-and-going with a preliminary move-things-and-break design. I obviously still need to clean things up quite a bit and refactor some things.

**Comment by dem1995** [comment]
The pull request is out there
